### ISSUE TITLE
multiple inheritance of pure virtual functions with the same name gives crash in some situation

### ISSUE THREAD

**Issue by labsin** [emscripten-core/emscripten-fastcomp#182] opened 2017-04-28 18:57 UTC
Clang crashes with:

```
clang-3.9: /home/sam/Apps/emsdk_portable/clang/fastcomp/src/tools/clang/lib/CodeGen/CGExprAgg.cpp:1561: void clang::CodeGen::CodeGenFunction::EmitAggregateCopy(clang::CodeGen::Address, clang::CodeGen::Address, clang::QualType, bool, bool): Assertion `(Record->hasTrivialCopyConstructor() || Record->hasTrivialCopyAssignment() || Record->hasTrivialMoveConstructor() || Record->hasTrivialMoveAssignment() || Record->isUnion()) && "Trying to aggregate-copy a type without a trivial copy/move " "constructor or assignment operator"' failed.
#0 0x0000559ea4012898 llvm::sys::PrintStackTrace(llvm::raw_ostream&) /home/sam/Apps/emsdk_portable/clang/fastcomp/src/lib/Support/Unix/Signals.inc:406:0
#1 0x0000559ea40106ae llvm::sys::RunSignalHandlers() /home/sam/Apps/emsdk_portable/clang/fastcomp/src/lib/Support/Signals.cpp:45:0
#2 0x0000559ea4010814 SignalHandler(int) /home/sam/Apps/emsdk_portable/clang/fastcomp/src/lib/Support/Unix/Signals.inc:246:0
#3 0x00007f8b01270670 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x11670)
#4 0x00007f8afffdc77f gsignal /build/glibc-cxyGtm/glibc-2.24/signal/../sysdeps/unix/sysv/linux/raise.c:58:0
#5 0x00007f8afffde37a abort /build/glibc-cxyGtm/glibc-2.24/stdlib/abort.c:91:0
#6 0x00007f8afffd4b47 __assert_fail_base /build/glibc-cxyGtm/glibc-2.24/assert/assert.c:92:0
#7 0x00007f8afffd4bf2 (/lib/x86_64-linux-gnu/libc.so.6+0x2dbf2)
#8 0x0000559ea4352c79 clang::CodeGen::CodeGenFunction::EmitAggregateCopy(clang::CodeGen::Address, clang::CodeGen::Address, clang::QualType, bool, bool) /home/sam/Apps/emsdk_portable/clang/fastcomp/src/tools/clang/lib/CodeGen/CGExprAgg.cpp:1555:0
#9 0x0000559ea41e1f18 clang::CodeGen::CodeGenFunction::EmitReturnOfRValue(clang::CodeGen::RValue, clang::QualType) /home/sam/Apps/emsdk_portable/clang/fastcomp/src/tools/clang/lib/CodeGen/CGStmt.cpp:1015:0
#10 0x0000559ea43f47c2 clang::CodeGen::CodeGenFunction::EmitCallAndReturnForThunk(llvm::Constant*, clang::ThunkInfo const*) /home/sam/Apps/emsdk_portable/clang/fastcomp/src/tools/clang/lib/CodeGen/CGVTables.cpp:335:0
#11 0x0000559ea43f4b1b clang::CodeGen::CodeGenFunction::generateThunk(llvm::Function*, clang::CodeGen::CGFunctionInfo const&, clang::GlobalDecl, clang::ThunkInfo const&) /home/sam/Apps/emsdk_portable/clang/fastcomp/src/tools/clang/lib/CodeGen/CGVTables.cpp:404:0
#12 0x0000559ea43f6601 clang::CodeGen::CodeGenVTables::emitThunk(clang::GlobalDecl, clang::ThunkInfo const&, bool) /home/sam/Apps/emsdk_portable/clang/fastcomp/src/tools/clang/lib/CodeGen/CGVTables.cpp:484:0
#13 0x0000559ea43f7c14 clang::CodeGen::CodeGenVTables::EmitThunks(clang::GlobalDecl) /home/sam/Apps/emsdk_portable/clang/fastcomp/src/tools/clang/lib/CodeGen/CGVTables.cpp:524:0
#14 0x0000559ea424fe1b clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) /home/sam/Apps/emsdk_portable/clang/fastcomp/src/tools/clang/lib/CodeGen/CodeGenModule.cpp:1873:0
#15 0x0000559ea4250079 clang::CodeGen::CodeGenModule::EmitDeferred() /home/sam/Apps/emsdk_portable/clang/fastcomp/src/tools/clang/lib/CodeGen/CodeGenModule.cpp:1361:0
#16 0x0000559ea4250234 clang::CodeGen::CodeGenModule::Release() /home/sam/Apps/emsdk_portable/clang/fastcomp/src/tools/clang/lib/CodeGen/CodeGenModule.cpp:378:0
#17 0x0000559ea484f097 (anonymous namespace)::CodeGeneratorImpl::HandleTranslationUnit(clang::ASTContext&) /home/sam/Apps/emsdk_portable/clang/fastcomp/src/tools/clang/lib/CodeGen/ModuleBuilder.cpp:257:0
#18 0x0000559ea484e9a5 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) /home/sam/Apps/emsdk_portable/clang/fastcomp/src/tools/clang/lib/CodeGen/CodeGenAction.cpp:173:0
#19 0x0000559ea4c49248 std::enable_if<std::__and_<std::is_move_constructible<bool>, std::is_move_assignable<bool> >::value, void>::type std::swap<bool>(bool&, bool&) /usr/include/c++/6/bits/move.h:192:0
#20 0x0000559ea4c49248 clang::ParseAST(clang::Sema&, bool, bool) /home/sam/Apps/emsdk_portable/clang/fastcomp/src/tools/clang/lib/Parse/ParseAST.cpp:161:0
#21 0x0000559ea484931a clang::CodeGenAction::ExecuteAction() /home/sam/Apps/emsdk_portable/clang/fastcomp/src/tools/clang/lib/CodeGen/CodeGenAction.cpp:911:0
#22 0x0000559ea4501876 clang::FrontendAction::Execute() /home/sam/Apps/emsdk_portable/clang/fastcomp/src/tools/clang/lib/Frontend/FrontendAction.cpp:459:0
#23 0x0000559ea44d40b6 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /home/sam/Apps/emsdk_portable/clang/fastcomp/src/tools/clang/lib/Frontend/CompilerInstance.cpp:954:0
#24 0x0000559ea4589cc2 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /home/sam/Apps/emsdk_portable/clang/fastcomp/src/tools/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:249:0
#25 0x0000559ea34c11a8 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /home/sam/Apps/emsdk_portable/clang/fastcomp/src/tools/clang/tools/driver/cc1_main.cpp:221:0
#26 0x0000559ea34834eb ExecuteCC1Tool /home/sam/Apps/emsdk_portable/clang/fastcomp/src/tools/clang/tools/driver/driver.cpp:299:0
#27 0x0000559ea34834eb main /home/sam/Apps/emsdk_portable/clang/fastcomp/src/tools/clang/tools/driver/driver.cpp:380:0
#28 0x00007f8afffc73f1 __libc_start_main /build/glibc-cxyGtm/glibc-2.24/csu/../csu/libc-start.c:325:0
#29 0x0000559ea34be14a _start (/home/sam/Apps/emsdk_portable/clang/fastcomp/build_incoming_64/bin/clang-3.9+0x7c614a)
Stack dump:
0.	Program arguments: /home/sam/Apps/emsdk_portable/clang/fastcomp/build_incoming_64/bin/clang-3.9 -cc1 -triple asmjs-unknown-emscripten -emit-llvm-bc -emit-llvm-uselists -disable-free -main-file-name multiple_virtual.cpp -mrelocation-model static -mthread-model posix -mdisable-fp-elim -no-integrated-as -mconstructor-aliases -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -coverage-notes-file /tmp/tmpOsNHyO/multiple_virtual_0.gcno -nostdsysteminc -nobuiltininc -resource-dir /home/sam/Apps/emsdk_portable/clang/fastcomp/build_incoming_64/bin/../lib/clang/4.0.0 -D __EMSCRIPTEN_major__=1 -D __EMSCRIPTEN_minor__=37 -D __EMSCRIPTEN_tiny__=9 -D _LIBCPP_ABI_VERSION=2 -c-isystem . -c-isystem /home/sam/Workspace/build-root/include -c-isystem /home/sam/Workspace/build-root/include -cxx-isystem . -cxx-isystem /home/sam/Workspace/build-root/include -Werror=implicit-function-declaration -std=c++03 -fdeprecated-macro -fno-dwarf-directory-asm -fdebug-compilation-dir /home/sam/Workspace/emscripten/test/multiple_pure_virtual -ferror-limit 19 -fmessage-length 80 -fobjc-runtime=gnustep -fcxx-exceptions -fexceptions -fdiagnostics-show-option -fcolor-diagnostics -nobuiltininc -nostdsysteminc -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/libcxx -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/lib/libcxxabi/include -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/compat -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/SSE -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/libc -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/lib/libc/musl/arch/emscripten -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/local/include -isystem/home/sam/Apps/emsdk_portable/emscripten/incoming/system/include/SDL -o /tmp/tmpOsNHyO/multiple_virtual_0.o -x c++ multiple_virtual.cpp 
1.	<eof> parser at end of file
2.	Per-file LLVM IR generation
3.	multiple_virtual.cpp:25:11: Generating code for declaration 'Derived::returnAType'
```

With the following example:

```cpp
class AType {
public:
    AType(): i(0) {
    }
    AType(const AType &other) {
    }
    AType &operator=(const AType &other) {
        return *this;
    }
    int i;
};

class Base1 {
public:
    virtual AType returnAType() = 0;
};

class Base2 {
public:
    virtual AType returnAType() = 0;
};

class Derived : public Base1, public Base2 {
public:
    AType returnAType() override {
        return AType();
    }
};

int main() {
    Derived d;
    AType a = d.returnAType();
    return 0;
}
```

Removing the copy or the move constructor, the problem isn't there.
Only deriving from one of the two base classes also fixes it.

This is with:
emscripten-incomming ba5bf7611182e3824f8d7e11d1defdbb507bb148
fastcomp: 084a1d917ea6172e7d65b9d8c254df843851ec98

Problem doesn't exist when building with for x86-64

**Comment by kripken** [comment] 2017-04-29 23:45
Confirmed, changing the triple makes this work.

Strange, we have very few differences at the clang level from the x86 target. This also works on the wasm32-unknown-unknown target, which we should have even fewer differences from.

I'd recommend looking in the code around that error, seeing what target customization hooks it uses.

**Comment by labsin** [comment] 2017-04-30 00:15
I checked with gdb the difference when building x86 and with emscripten target it doesn't call https://github.com/kripken/emscripten-fastcomp-clang/blob/incoming/lib/CodeGen/CGVTables.cpp#L320

CurFnInfo->getReturnInfo().getKind() == ABIArgInfo::Indirect resolves to false with emscripten (I think)
Later with the emscripten target, it does issues CGM.getCXXABI().EmitReturnFromThunk(*this, RV, ResultType); and the x86 target doesn't.

This is when it processes the virtual function.

Don't know anything about the code.

**Comment by labsin** [comment] 2017-04-30 12:49
I found the difference with wasm:
https://github.com/kripken/emscripten-fastcomp-clang/blob/incoming/lib/CodeGen/TargetInfo.cpp#L788
That isn't there with the emscripten implementation.
Also the computeInfo is changed.

I am now building with the attached patch. But my pc is slow and linking clang needs swap memory cause I have to little so i can't try building different things. And my system gcc compiler was updated so cmake is rebuilding everything.

[mult_inh.txt](https://github.com/kripken/emscripten-fastcomp/files/966725/mult_inh.txt)

**Comment by labsin** [comment] 2017-04-30 18:24
Proposed a merge. https://github.com/kripken/emscripten-fastcomp-clang/pull/17
Haven't run any test. It seems you also have a similar pull request open.

Btw. I linked clang with the gold linker and it completed in 3min. The default linker took a whole night (to little memory)

**Comment by kripken** [comment] 2017-05-01 21:38
Interesting it's similar to that other PR. I'll try what you mentioned there.

Did you notice if that other PR also fixes your issue here? Or are both PRs needed?

**Comment by labsin** [comment] 2017-05-01 21:53
No. Only saw that one later. I only copied the differences with the wasm. I also had to rebuild the cache.
Did you actually considered using the gold linker default/adding an option to the SDK. It really helped me.

**Comment by kripken** [comment] 2017-05-01 21:59
Ok, I verified locally now, the other PR does fix your testcase. So I think we just need to merge that one.

About gold, yeah, I've seen it use a lot less memory. It can be dramatically faster on some machines due to that. I'm not sure though how easy it would be to use it in the sdk.

**Comment by labsin** [comment] 2017-05-01 22:12
To link llvm and clang with gold you just need to pass -DLLVM_USE_LINKER=gold to cmake when you configure llvm and clang.

**Comment by kripken** [comment] 2017-05-01 22:51
Yeah, I guess the question is how easy it is for the sdk build infrastructure to bundle gold.

Meanwhile I merged that other PR, so it should fix your testcase too (and make that PR unnecessary), please confirm.

**Comment by juj** [comment] 2017-05-03 13:18
Sounds like a big benefit to enable support for linking with gold. Added a feature to emsdk script to allow specifying parameters such as `-DLLVM_USE_LINKER=gold` to the build. See https://github.com/juj/emsdk/commit/14d6a48a169ae347b11b4c609f907965624fc491 for details.

**Comment by bsed** [comment] 2017-06-20 12:33
Unable to open '??': File not found (/??).

**Closed** 2021-11-01 15:52 UTC
